- hosts: localhost
  gather_facts: no
  vars:
    terraform_directory: "/home/hazem/AWS-Ansible-WinServer"  # Update with the path to your Terraform files
    private_key_path: "/home/hazem/.ssh/id_rsa"  # Update with the path to your private key
    bash_script_path: "/home/hazem/AWS-Ansible-WinServer/Instance_Pass.sh"

  tasks:
    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: "{{ terraform_directory }}"

    - name: Apply Terraform
      command: terraform apply -auto-approve
      args:
        chdir: "{{ terraform_directory }}"

    - name: Execute Bash Script to Decrypt Password
      command: "{{ bash_script_path }}"
      register: bash_script_output

    - name: Display Decrypted Password
      debug:
        var: bash_script_output.stdout_lines